### ISSUE TITLE
How to / how

### ISSUE THREAD

**Issue by tmcw** [LegalServicesCorporation/LSC-Mapping#9]
Sorry about the sudden influx of undocumented code - here's what it's doing and how it works:

The site is designed to be static - it can be on a basic server like [GitHub Pages](http://pages.github.com/) or S3 or so on. You can drop it into a file directory in a Drupal site and it should work.

All of the shapes in the KML file are too many to push to a browser, so this cheats in two ways:
1. It splits up each shape into a separate file, under `areas/{id}.geojson`
2. It creates a file that lists all bounding boxes of all features, under `index.json`

It makes these two files by running [node.js](http://nodejs.org/) - you could rewrite these scripts in python or so on. The only 'hard part' is [point in polygon searching](http://en.wikipedia.org/wiki/Point_in_polygon), which is pretty simple to implement once you get the hang of it.

First a search runs through a geocoder to turn a plain-english string like 'Chester, NJ' into a point in latitude/longitude. Then it's matched against all bounding boxes, and matching bounding boxes are double-checked with a point-in-polygon search to make sure that the point is really in them, not just on the cusp or in a hole. Then the shape is added to the map and the information is added in a div.

If you just want to serve this file off of github, make a `gh-pages` branch, and it'll be available under `{yourusername}.github.io/LSC-Mapping`.

I used [GDAL](http://www.gdal.org/) to convert the given KML file into [GeoJSON](http://geojson.org/), which is a simpler format that's easier to use in browsers. I did this with:

```
ogr2ogr -f GeoJSON all.geojson lsc.kml
```

This `all.geojson` file that's generated is what feeds the scripts that create the index and the individual area geojson files.

**Comment by tmcw** [comment]
Oh, and demo: http://macwright.org/LSC-Mapping/

**Comment by tmcw** [comment]
Future work is basically updating the KML, and then

```
node bbox.js
node areas.js
```

And you should be set. Extracting the `RNO_` value, you'll need to write a regular expression or use jQuery to pull the number from the page.

**Comment by tuckera** [comment]
Hi Tom,

My name is Alex Tucker & I'm a colleague of Jessie Posilkin & Peter Campbell at Legal Services Corporation.

Following your instructions above for making the LSC Locator interactive map work in Drupal, I copied the folder containing the files & pasted it into the sites/default/files/ location on our LSC.gov Drupal dev site.

Then I tested using the sites/default/files/Find-Legal-Aid-Map-files/index.html URL & was able to view the LSC Locator map.

However, when I enter a zip code in the search field & click Search, nothing happens.

Any thoughts on how to make this work?

Regards,
Alex

**Comment by tmcw** [comment]
the first step will be [enable browser debug tools](http://debugbrowser.com/) and see if there are any error messages. Also, this is not tested in Internet Explorer and, like everything, probably has bugs in it and would need to use [underscore](http://underscorejs.org/) or similar if you really want to support old IEs.

**Comment by tuckera** [comment]
Using the Network section of the Google Chrome Developer Tools, I compared your map located at http://legalservicescorporation.github.io/LSC-Mapping/ to the one we posted on our Drupal dev site & the files matched. 

I also posted the LSC-Mapping folder & files from GitHub to a non-Drupal site but encountered the same issue where the search feature doesn't work.

There's a 404 Not Found error for the jquery-2.0.3.min.map file on both your map & ours, so I don't think that's causing the problem.

Any other thoughts on what's causing the issue?

**Comment by tmcw** [comment]
> Any other thoughts on what's causing the issue?

I can't really debug without more information. Any errors in the console, any link to a live example?

**Comment by tuckera** [comment]
I don't see any errors in the console.

Here'sour dev site login information:
http://lsc.dev.advomatic.com/sites/default/files/LSC-Mapping/index.html
User Name: lsc
Password: a6SRnFqyjrgC

**Comment by tmcw** [comment]
Your web server is responding to a request for `http://lsc.dev.advomatic.com/sites/default/files/LSC-Mapping/master.json` with a content type of `text/plain`, which triggers jQuery to read it as a  string rather than a JSON file. You can either [set the dataType](http://api.jquery.com/jQuery.ajax/) of that ajax request to fix the issue, or correct the server to send a proper header, like `application/json`
